import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        sidebar: "var(--sidebar)",
        card: "var(--card)",
        "card-hover": "var(--card-hover)",
        input: "var(--input)",
        overlay: "var(--overlay)",
        border: "var(--border)",
        "border-hover": "var(--border-hover)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-muted": "var(--accent-dim)",
        "accent-border": "var(--accent-border)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "on-accent": "var(--on-accent)",
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
        info: "var(--info)",
        "success-muted": "var(--success-muted)",
        "warning-muted": "var(--warning-muted)",
        "danger-muted": "var(--danger-muted)",
        "info-muted": "var(--info-muted)",
        "status-done": "var(--success)",
        "status-running": "var(--warning)",
        "status-waiting": "var(--border-hover)",
        "chart-normal": "var(--success)",
        "chart-low": "var(--info)",
        "chart-high": "var(--danger)",
        "chart-critical": "#A84455",
        "summary-text": "var(--text-secondary)",
        "action-text": "var(--text-primary)",
        "sidebar-footer": "var(--text-tertiary)",
        ink: {
          deep: "#0F1018",
          black: "#14161E",
          slate: "#1E2028",
          gray: "#8E92A8",
          light: "#C8CADB",
          paper: "#E8EAF2",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: [
          "var(--font-display)",
          "Cormorant Garamond",
          "EB Garamond",
          "Playfair Display",
          "serif",
        ],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        card: "16px",
        element: "10px",
      },
      letterSpacing: {
        logo: "0.5px",
        "display-tight": "-1.5px",
      },
    },
  },
  plugins: [],
};
export default config;
