import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#1E2028",
        sidebar: "#191B22",
        card: "#252830",
        "card-hover": "#2C2F3A",
        input: "#1E2028",
        overlay: "#252830",
        border: "#32364A",
        "border-hover": "#3E4260",
        accent: "#4ECBA8",
        "accent-hover": "#62DDB8",
        "accent-muted": "#4ECBA815",
        "accent-border": "#4ECBA840",
        "text-primary": "#E8EAF2",
        "text-secondary": "#C8CADB",
        "text-tertiary": "#8E92A8",
        "on-accent": "#191B22",
        success: "#4ECBA8",
        warning: "#D4956A",
        danger: "#C4617A",
        info: "#6B8FCC",
        "success-muted": "#4ECBA810",
        "warning-muted": "#D4956A10",
        "danger-muted": "#C4617A10",
        "info-muted": "#6B8FCC10",
        "status-done": "#4ECBA8",
        "status-running": "#D4956A",
        "status-waiting": "#3E4260",
        "chart-normal": "#4ECBA8",
        "chart-low": "#6B8FCC",
        "chart-high": "#C4617A",
        "chart-critical": "#A84455",
        "summary-text": "#C8CADB",
        "action-text": "#E8EAF2",
        "sidebar-footer": "#8E92A8",
        ink: {
          deep: "#0F1018",
          black: "#14161E",
          slate: "#1E2028",
          gray: "#8E92A8",
          light: "#C8CADB",
          paper: "#E8EAF2",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: [
          "var(--font-display)",
          "Cormorant Garamond",
          "EB Garamond",
          "Playfair Display",
          "serif",
        ],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        card: "16px",
        element: "10px",
      },
      letterSpacing: {
        logo: "0.5px",
        "display-tight": "-1.5px",
      },
    },
  },
  plugins: [],
};
export default config;
