import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0C0C0F",
        sidebar: "#09090C",
        card: "#13131A",
        "card-hover": "#17171F",
        input: "#0F0F14",
        overlay: "#1A1A24",
        border: "#1E1E2E",
        "border-hover": "#2A2A3E",
        "border-active": "#3D3D5C",
        accent: "#00D4AA",
        "accent-hover": "#00F0C0",
        "accent-muted": "#00D4AA18",
        "accent-border": "#00D4AA40",
        "text-primary": "#F0EEF8",
        "text-secondary": "#9896A8",
        "text-tertiary": "#4E4C5E",
        "on-accent": "#0C0C0F",
        success: "#00D4AA",
        warning: "#F5A623",
        danger: "#FF4D6A",
        info: "#4D9FFF",
        "success-muted": "#00D4AA12",
        "warning-muted": "#F5A62312",
        "danger-muted": "#FF4D6A12",
        "info-muted": "#4D9FFF12",
        "status-done": "#00D4AA",
        "status-running": "#F5A623",
        "status-waiting": "#4E4C5E",
        "chart-normal": "#00D4AA",
        "chart-low": "#4D9FFF",
        "chart-high": "#FF4D6A",
        "chart-critical": "#FF1744",
        "summary-text": "#D8D6E8",
        "action-text": "#C8C6D8",
        "sidebar-footer": "#3A3850",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-fraunces)", "Fraunces", "Georgia", "serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        card: "16px",
        element: "10px",
      },
      letterSpacing: {
        logo: "-0.3px",
        "display-tight": "-0.5px",
      },
    },
  },
  plugins: [],
};
export default config;
